Repository hacku-chamomilla/doutankyohi-back-end, pull requests merged in 2023-02, with the labels that each got.

#24 Add＿playerの実装
  server.go
  src/use_DB/add_player.go
  src/use_DB/create_db.go
  src/use_DB/get_hint_list.go
Labels: feature

#25 PlayerListの実装
  server.go
  src/use_DB/player_list.go
Labels: block, feature

#26 Themeを取得する関数の実装
  server.go
  src/use_DB/get_theme.go
Labels: block, feature

#28 CreateThemeの実装
  server.go
  src/use_DB/create_theme.go
Labels: block, feature

#30 ヒントの入力の実装
  server.go
  src/use_DB/create_hint.go
  src/use_DB/create_theme.go
  src/use_DB/get_theme.go
Labels: block, feature

#19 テストの CI の作成
  .github/workflows/test.yml
Labels: block

#32 DeleteHintの実装
  server.go
  src/use_DB/add_player.go
  src/use_DB/delete_hint.go
  src/use_DB/player_list.go
Labels: block, feature

#33 Stepの実装が
  server.go
  src/use_DB/get_step.go
Labels: block, feature

#61 deleteのエラーの修正
  src/use_DB/delete_hint.go
Labels: refactoring

#52 get-roleのAPIの追加
  server.go
  src/use_DB/get_role.go
Labels: feature

#41 Get_hint_listの実装
  server.go
  src/use_DB/get_hint_list.go
Labels: feature

#45 random_themeの実装
  server.go
  src/use_DB/get_random_theme.go
Labels: feature

#76 各処理を行ったらstepを進める
  server.go
  src/use_DB/add_player.go
  src/use_DB/create_hint.go
  src/use_DB/create_theme.go
  src/use_DB/deceide_theme.go
  src/use_DB/delete_hint.go
  src/use_DB/is_currect.go
  src/use_DB/start_game.go
  src/use_DB/update_answer.go
Labels: feature

#80 ゲーム終了時の処理の実装
  server.go
  src/use_DB/end_game.go
Labels: feature

#82 choice-theme
  src/use_DB/create_theme.go
Labels: feature

#84 Keyの値の変更
  src/use_DB/get_hint_list.go
Labels: feature

#86 plyerIdの追加
  src/use_DB/get_hint_list.go
Labels: feature

#88 IDでの削除
  src/use_DB/delete_hint.go
Labels: feature

#90 roleをintに修正
  src/use_DB/start_game.go
Labels: bug

#95 HowToDecideThemeが１の時にランダムにテーマ取得
  server.go
  src/use_DB/deceide_theme.go
Labels: bug

#99 HIntの上書き
  src/use_DB/delete_hint.go
Labels: bug

#101 fix: create_themeの修正
  src/use_DB/create_theme.go
Labels: bug

#97 create_themeのstepの位置の修正
  src/use_DB/create_theme.go
Labels: bug

#107 人狼の追加によるプレイヤーの情報の追加
  server.go
  src/use_DB/add_player.go
  src/use_DB/player_list.go
Labels: feature

#109 voteの実装
  server.go
  src/use_DB/vote.go
Labels: feature

#111 choice-wolfの実装
  server.go
  src/use_DB/choice-wolf.go
Labels: feature

#112 JudgementWolfの実装
  server.go
  src/use_DB/judgement_wolf.go
Labels: feature

#117 ModeWolfの実装
  server.go
  src/use_DB/is_mode_wolf.go
Labels: feature

#120 feat: playerlist-wolfの実装
  server.go
  src/use_DB/add_player.go
  src/use_DB/player_list_wolf.go
Labels: feature

#123 get-role-wolfの実装
  server.go
  src/use_DB/get_role_wolf.go
Labels: feature

#124 retuernの値の形を変えた
  server.go
  src/use_DB/choice-wolf.go
Labels: feature

#125 fix: voteの修正
  server.go
  src/use_DB/start_game.go
  src/use_DB/vote.go
Labels: feature

#133 point計算
  server.go
  src/use_DB/create_db.go
  src/use_DB/judgement_wolf.go
  src/use_DB/point.go
Labels: feature

#135 get-wolf-nameの実装
  server.go
  src/use_DB/get_wolf_name.go
Labels: feature

#59 コマンドの実行時のマニュアル実装
  command.md
  src/use_DB/add_player.go
  src/use_DB/create_hint.go
  src/use_DB/create_theme.go
  src/use_DB/deceide_theme.go
  src/use_DB/delete_hint.go
  src/use_DB/end_game.go
  src/use_DB/get_hint_list.go
  src/use_DB/get_step.go
  src/use_DB/is_currect.go
  src/use_DB/player_list.go
  src/use_DB/start_game.go
  src/use_DB/update_answer.go
Labels: documentation
